version: 2

models:

  - name: int_order_items
    description: "Intermediate model containing transformed order item data"

    columns:
      - name: order_item_id
        description: "Unique identifier for each order item"
        data_tests:
          - not_null
          - unique

      - name: order_id
        description: "Order associated with the order item"
        data_tests:
          - not_null
          - relationships:
              arguments:
                to: ref('stg_orders')
                field: order_id

      - name: product_id
        description: "Product associated with the order item"
        data_tests:
          - not_null
          - relationships:
              arguments:
                to: ref('stg_products')
                field: product_id


  - name: int_orders
    description: "Intermediate model containing transformed order data"

    columns:
      - name: order_id
        description: "Unique identifier for each order"
        data_tests:
          - not_null
          - unique

      - name: customer_id
        description: "Customer associated with the order"
        data_tests:
          - not_null
          - relationships:
              arguments:
                to: ref('stg_customers')
                field: customer_id


  - name: int_customers
    description: "Intermediate model containing transformed customer data"

    columns:
      - name: customer_id
        description: "Unique identifier for each customer"
        data_tests:
          - not_null
          - unique